- Rakefile
Because libyaml is no longer bundled in psych since https://github.com/ruby/ruby/pull/5693 https://github.com/ruby/psych/pull/541
> Build libyaml as a dependency

- .clang-format
- Rakefile
- ext/witapi/bindgen/rb-abi-guest.wit
- ext/witapi/witapi-core.c
- packages/npm-packages/ruby-wasm-wasi/build-package.sh
- packages/npm-packages/ruby-wasm-wasi/src/index.ts
- packages/npm-packages/ruby-wasm-wasi/test/vm.test.ts
Resolve https://github.com/ongaeshi/rubyonbrowser/issues/14
> Protect lending objects having same hash values from GC

- CONTRIBUTING.md
- README.md
- Rakefile
- ext/js/js-core.c
- lib/ruby_wasm/build_system/downloader.rb
- lib/ruby_wasm/build_system/product/baseruby.rb
- lib/ruby_wasm/build_system/product/crossruby.rb
- lib/ruby_wasm/rake_task.rb
- packages/npm-packages/ruby-wasm-wasi/.prettierignore
- packages/npm-packages/ruby-wasm-wasi/rollup.config.js
- packages/npm-packages/ruby-wasm-wasi/src/browser.script.ts
- packages/npm-packages/ruby-wasm-wasi/src/index.ts
- packages/npm-packages/ruby-wasm-wasi/test/init.ts
- packages/npm-packages/ruby-wasm-wasi/test/js_from_rb.test.ts
- tasks/format.rake
Added build instructions in CONTRIBUTING.md, and added code formatting policy
> Improve contribution experience

- packages/npm-packages/ruby-wasm-wasi/src/browser.script.ts
- Parallelization of downloads
- Error response handling
- URL encoding
> Improve loading of Ruby scripts when using the src attribute

- lib/ruby_wasm/build_system/product/ruby_source.rb
To embed build revision in binaries
> Fetch source via git instead of tarball

- ext/js/lib/js.rb
- packages/npm-packages/ruby-wasm-wasi/test/js_from_rb.test.ts
> Add JS::Undefined and JS::Null

- packages/npm-packages/ruby-wasm-wasi/src/browser.ts
> Postpone writing to stdout/stderr until a newline arrives

- packages/npm-packages/ruby-3_2-wasm-wasi/package-lock.json
- packages/npm-packages/ruby-3_2-wasm-wasi/package.json
- packages/npm-packages/ruby-3_2-wasm-wasi/rollup.config.mjs
- packages/npm-packages/ruby-head-wasm-wasi/rollup.config.mjs
- packages/npm-packages/ruby-wasm-wasi/package-lock.json
- packages/npm-packages/ruby-wasm-wasi/package.json
- packages/npm-packages/ruby-wasm-wasi/rollup.config.mjs
> Bundle `Buffer` to all browser scripts

- .github/workflows/build.yml
- builders/wasm32-unknown-wasi/Dockerfile
https://docs.docker.com/build/cache/backends/gha/#using-dockerbuild-push-action
> Speed up builder build

- packages/npm-packages/ruby-wasm-wasi/src/browser.ts
- packages/npm-packages/ruby-wasm-wasi/src/node.ts
- packages/npm-packages/ruby-wasm-wasi/test-e2e/integrations/browser-script.spec.ts
Resolve https://github.com/ruby/ruby.wasm/issues/234
> Extend default fiber stack size tentatively

- ext/js/js-core.c
Close https://github.com/ruby/ruby.wasm/issues/269
> Fix doc example for JS::Object#call

- packages/npm-packages/ruby-wasm-wasi/tools/pack-compat-shim.mjs
Close https://github.com/ruby/ruby.wasm/issues/282
> packaging: Remove deprecated warning for browser.{esm,umd}.js

- builders/wasm32-unknown-emscripten/Dockerfile
- builders/wasm32-unknown-wasi/Dockerfile
Also setup_xx.x is deprecated now. Use deb package directly instead.
> Update Node.js version 16 -> 20

- ext/witapi/witapi-core.c
The workaround was introduced to address script-encoding issues in rb_eval_string. However, we don't need to use C API especially for eval because we can use `Kernel#eval` from C instead.
> witapi: Remove private API use for eval

- .github/workflows/build.yml
- Rakefile
- lib/ruby_wasm/packager/file_system.rb
- rakelib/format.rake
- rakelib/packaging.rake
- test/test_build_smoke.rb
Fix https://github.com/kateinoigakukun/ruby-compute-runtime/issues/13
TODO: Add test suites
> Package all files in packaged .gem

- packages/npm-packages/ruby-wasm-wasi/test/init.js
- packages/npm-packages/ruby-wasm-wasi/test/vm.test.js
https://bugs.ruby-lang.org/issues/19117
This repairs the head CI job
> Accept new style backtrace for Ruby 3.4

- .github/workflows/build.yml
- builders/wasm32-unknown-emscripten/Dockerfile
- builders/wasm32-unknown-wasi/Dockerfile
- lib/ruby_wasm/cli.rb
- rakelib/packaging.rake
- sig/ruby_wasm/cli.rbs
https://github.com/ruby/ruby/commit/bc7266c5ce51b170c107011c712f97b4dc8243a6
> Bump minimum baseruby version to 3.0

- packages/gems/js/ext/js/js-core.c
- packages/npm-packages/ruby-wasm-wasi/test/unit/test_object.rb
Close https://github.com/ruby/ruby.wasm/issues/395
> Accept JS::Object like object in JS::Object#==

- packages/npm-packages/ruby-wasm-wasi/src/vm.ts
Mitigation for https://github.com/ruby/ruby.wasm/issues/577
> Suggest adding `gem "js"` to Gemfile when failing to instantiate Ruby VM

- .github/workflows/build.yml
- .github/workflows/nightly-release.yml
Ubuntu 20.04 support in GitHub Actions is going to be EOL
> ci: Update to Ubuntu 24.04
